export * as ai from './ai/$plugin';
export * as core from './core/$plugin';
export * as ct from './ct/$plugin';
export * as duck from './duck/$plugin';
export * as fc from './fc/$plugin';
export * as games from './games/$plugin';
export * as op from './op/$plugin';
export * as pets from './pets/$plugin';
export * as pokecom from './pokecom/$plugin';
